# If true, players can only set their visit location at locations deemed safe.
# Players can also not visit locations that have become unsafe.
Safe-Teleport: true

# If true, visit locations will always default to having the player look straight ahead.
# If false, visit locations can have players looking straight up, straight down, or anywhere in-between.
Center-Up-Down: true

# Nearest degree to round view rotation to for visit locations.
# Value of 90 will snap to North, South, East, and West.
# Value of 45 will snap to four major cardinal directions, as well as North-East, North-West, South-East, and South-West.
# Set this value to 0 to disable it.
Cardinal-Rounding: 45

# Sets default behavior for whether people will receive messages when someone visits them.
# If true, players will receive visit notifications by default, and will have to manually disable them.
# If false, players will not receive visit notifications, and will have to manually turn them on.
# Message settings can be changed in-game with /visitcfg messages on/off
Messages-Default-On: true

# How many players can be shown on the visit GUI at one time.
# Must be a multiple of 9 between 9 and 45 (last row of GUI will always be reserved for page navigation tools)
# The GUI will only show as many rows as it needs at one time, no matter the max.
# I advise leaving this value at 45 to get the most out of it. If you need to go smaller, 27 is a good value as well.
Max-Players-Per-Page: 45

# Commands outside of this plugin that will set a players visit location, without having to type /setvisit
# Most common use case would be wanting a players Essentials home to be their visit location.
# Multiple commands are allowed, just do a new line with a '-' before each command, like shown below.
# Remove the '#' from in front of the sethome command below to enable it.
Custom-Set-Visit-Commands:
#  - sethome

# Should this command work if there are arguments after the custom command, or only when the custom command is used alone?
# If false, the plugin will only set visit when a command is used without any arguments. 
# For example, it would work with /sethome, but not with /sethome Cave.
# If true, this will work so long as the command used is on the list, no matter the arguments.
# So this would work if the player used /sethome or /sethome Cave.
Allow-Additional-Parameters: false

# Should the player be sent the message that their visit location has been set when using custom commands?
# If true, /sethome would send a message saying they set their visit, along with the default Essentials sethome message.
# If false, /sethome would only send the default Essentials sethome message.
Send-Message-On-Custom-Command: true

# If true, players cannot use the /setvisit or /delvisit commands.
# Visit locations can only be set by custom commands set above, or when set by another plugin.
# Used if you do not want players to have control of their visit location.
# Players can still use visit commands, and configure their notification settings.
Block-Set-Visit-Command: false