name: Visit
main: com.skyblockedmc.visit.Visit
version: ${version}
description: Plugin to easily visit other players
author: RedstoneTrails
load: startup
api-version: 1.13
commands:
     setvisit:
         description: Sets player's visit location
         usage: /setvisit
     delvisit:
         description: Deletes player's visit location
         usage: /delvisit
     visit:
         description: Lets player visit another player's visit location
         usage: /visit
     players:
         description: Pops up GUI of all available players to visit
         usage: /players
         aliases: [visits]
     visitcfg:
         description: Allows customization of visit plugin
         usage: /visitcfg help
         aliases: [vcfg]